### ISSUE TITLE
Inmembrane: Installation and Configuration

### ISSUE THREAD

**Issue by Dimpledavray287** [boscoh/inmembrane#5]
Dear Andrew,
Hi had installed inmembrane via github with given below command.
$ git clone http://github.com/boscoh/inmembrane.git

Later while given below command were executed but found issues. I have pasted log file. KINDLY GUIDE ME. 
cd inmembrane
$ sudo python setup.py install

Error as given below :- 

1) **byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/__init__.py to __init__.cpython-38.pyc
  File "/usr/local/lib/python3.8/dist-packages/inmembrane/__init__.py", line 115
    def process(params):
    ^
SyntaxError: import * only allowed at module level**

2) File "/usr/local/lib/python3.8/dist-packages/inmembrane/plugins/tmhmm_web.py", line 75
    newseqid = `seqcount` + re.sub(r'[^\w]', "", seqid)
               ^
SyntaxError: invalid syntax

3) File "/usr/local/lib/python3.8/dist-packages/inmembrane/helpers.py", line 89
    print s
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(s)?

**Log file** 

sudo python setup.py install
[sudo] password for dimple: 
/usr/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
/usr/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'zip_safe'
  warnings.warn(msg)
running install
running build
running build_py
creating build
creating build/lib
creating build/lib/inmembrane
copying inmembrane/__init__.py -> build/lib/inmembrane
copying inmembrane/helpers.py -> build/lib/inmembrane
creating build/lib/inmembrane/plugins
copying inmembrane/plugins/bomp_web.py -> build/lib/inmembrane/plugins
copying inmembrane/plugins/hmmsearch3.py -> build/lib/inmembrane/plugins
copying inmembrane/plugins/tmbetadisc_rbf_web.py -> build/lib/inmembrane/plugins
copying inmembrane/plugins/lipop_scrape_web.py -> build/lib/inmembrane/plugins
copying inmembrane/plugins/__init__.py -> build/lib/inmembrane/plugins
copying inmembrane/plugins/tmbhunt_web.py -> build/lib/inmembrane/plugins
copying inmembrane/plugins/tmhmm_web.py -> build/lib/inmembrane/plugins
copying inmembrane/plugins/memsat3.py -> build/lib/inmembrane/plugins
copying inmembrane/plugins/tmhmm.py -> build/lib/inmembrane/plugins
copying inmembrane/plugins/lipop1.py -> build/lib/inmembrane/plugins
copying inmembrane/plugins/tmhmm_scrape_web.py -> build/lib/inmembrane/plugins
copying inmembrane/plugins/lipop_web.py -> build/lib/inmembrane/plugins
copying inmembrane/plugins/signalp4.py -> build/lib/inmembrane/plugins
copying inmembrane/plugins/signalp_scrape_web.py -> build/lib/inmembrane/plugins
copying inmembrane/plugins/tatfind_web.py -> build/lib/inmembrane/plugins
creating build/lib/inmembrane/protocols
copying inmembrane/protocols/gram_pos.py -> build/lib/inmembrane/protocols
copying inmembrane/protocols/__init__.py -> build/lib/inmembrane/protocols
copying inmembrane/protocols/gram_neg.py -> build/lib/inmembrane/protocols
creating build/lib/inmembrane/tests
copying inmembrane/tests/test_misc.py -> build/lib/inmembrane/tests
copying inmembrane/tests/test_bomp_web.py -> build/lib/inmembrane/tests
copying inmembrane/tests/test_signalp_scrape_web.py -> build/lib/inmembrane/tests
copying inmembrane/tests/__init__.py -> build/lib/inmembrane/tests
copying inmembrane/tests/test_signalp4.py -> build/lib/inmembrane/tests
copying inmembrane/tests/test_tatfind_web.py -> build/lib/inmembrane/tests
copying inmembrane/tests/test_hmmsearch3.py -> build/lib/inmembrane/tests
copying inmembrane/tests/test_tmbetadisc_rbf_web.py -> build/lib/inmembrane/tests
copying inmembrane/tests/test_tmhmm_scrape_web.py -> build/lib/inmembrane/tests
copying inmembrane/tests/PluginTestBase.py -> build/lib/inmembrane/tests
copying inmembrane/tests/test_lipop_scrape_web.py -> build/lib/inmembrane/tests
copying inmembrane/tests/test_tmhmm.py -> build/lib/inmembrane/tests
copying inmembrane/tests/test_lipop1.py -> build/lib/inmembrane/tests
copying inmembrane/tests/test_memsat3.py -> build/lib/inmembrane/tests
creating build/lib/inmembrane/protocols/gram_neg_profiles
copying inmembrane/protocols/gram_neg_profiles/Tat_PS51318.hmm -> build/lib/inmembrane/protocols/gram_neg_profiles
creating build/lib/inmembrane/protocols/gram_pos_profiles
copying inmembrane/protocols/gram_pos_profiles/SLH.hmm -> build/lib/inmembrane/protocols/gram_pos_profiles
copying inmembrane/protocols/gram_pos_profiles/LPxTG_PS50847.hmm -> build/lib/inmembrane/protocols/gram_pos_profiles
copying inmembrane/protocols/gram_pos_profiles/NLPC_P60.hmm -> build/lib/inmembrane/protocols/gram_pos_profiles
copying inmembrane/protocols/gram_pos_profiles/GW2.hmm -> build/lib/inmembrane/protocols/gram_pos_profiles
copying inmembrane/protocols/gram_pos_profiles/GW3.hmm -> build/lib/inmembrane/protocols/gram_pos_profiles
copying inmembrane/protocols/gram_pos_profiles/Gram_pos_anchor.hmm -> build/lib/inmembrane/protocols/gram_pos_profiles
copying inmembrane/protocols/gram_pos_profiles/LPxTG.hmm -> build/lib/inmembrane/protocols/gram_pos_profiles
copying inmembrane/protocols/gram_pos_profiles/PG_binding_2.hmm -> build/lib/inmembrane/protocols/gram_pos_profiles
copying inmembrane/protocols/gram_pos_profiles/GW1.hmm -> build/lib/inmembrane/protocols/gram_pos_profiles
copying inmembrane/protocols/gram_pos_profiles/PG_binding_3.hmm -> build/lib/inmembrane/protocols/gram_pos_profiles
copying inmembrane/protocols/gram_pos_profiles/CW_binding_2.hmm -> build/lib/inmembrane/protocols/gram_pos_profiles
copying inmembrane/protocols/gram_pos_profiles/LysM.hmm -> build/lib/inmembrane/protocols/gram_pos_profiles
copying inmembrane/protocols/gram_pos_profiles/PG_binding_1.hmm -> build/lib/inmembrane/protocols/gram_pos_profiles
copying inmembrane/protocols/gram_pos_profiles/CW_binding_1.hmm -> build/lib/inmembrane/protocols/gram_pos_profiles
creating build/lib/inmembrane/tests/signalp_scrape_web
copying inmembrane/tests/signalp_scrape_web/input.fasta -> build/lib/inmembrane/tests/signalp_scrape_web
creating build/lib/inmembrane/tests/tmhmm_scrape_web
copying inmembrane/tests/tmhmm_scrape_web/input.fasta -> build/lib/inmembrane/tests/tmhmm_scrape_web
creating build/lib/inmembrane/tests/memsat3
copying inmembrane/tests/memsat3/input.fasta -> build/lib/inmembrane/tests/memsat3
creating build/lib/inmembrane/tests/tatfind_web
copying inmembrane/tests/tatfind_web/input.fasta -> build/lib/inmembrane/tests/tatfind_web
creating build/lib/inmembrane/tests/signalp4
copying inmembrane/tests/signalp4/input.fasta -> build/lib/inmembrane/tests/signalp4
creating build/lib/inmembrane/tests/lipop_scrape_web
copying inmembrane/tests/lipop_scrape_web/input.fasta -> build/lib/inmembrane/tests/lipop_scrape_web
creating build/lib/inmembrane/tests/lipop1
copying inmembrane/tests/lipop1/input.fasta -> build/lib/inmembrane/tests/lipop1
creating build/lib/inmembrane/tests/tmhmm
copying inmembrane/tests/tmhmm/input.fasta -> build/lib/inmembrane/tests/tmhmm
creating build/lib/inmembrane/tests/hmmsearch3
copying inmembrane/tests/hmmsearch3/input.fasta -> build/lib/inmembrane/tests/hmmsearch3
creating build/lib/inmembrane/tests/tmbetadisc_rbf_web
copying inmembrane/tests/tmbetadisc_rbf_web/input.fasta -> build/lib/inmembrane/tests/tmbetadisc_rbf_web
creating build/lib/inmembrane/tests/bomp_web
copying inmembrane/tests/bomp_web/input.fasta -> build/lib/inmembrane/tests/bomp_web
running build_scripts
creating build/scripts-3.8
copying and adjusting inmembrane_scan -> build/scripts-3.8
changing mode of build/scripts-3.8/inmembrane_scan from 644 to 755
running install_lib
copying build/lib/inmembrane/protocols/gram_pos.py -> /usr/local/lib/python3.8/dist-packages/inmembrane/protocols
copying build/lib/inmembrane/protocols/__init__.py -> /usr/local/lib/python3.8/dist-packages/inmembrane/protocols
copying build/lib/inmembrane/protocols/gram_neg.py -> /usr/local/lib/python3.8/dist-packages/inmembrane/protocols
copying build/lib/inmembrane/protocols/gram_neg_profiles/Tat_PS51318.hmm -> /usr/local/lib/python3.8/dist-packages/inmembrane/protocols/gram_neg_profiles
copying build/lib/inmembrane/protocols/gram_pos_profiles/SLH.hmm -> /usr/local/lib/python3.8/dist-packages/inmembrane/protocols/gram_pos_profiles
copying build/lib/inmembrane/protocols/gram_pos_profiles/LPxTG_PS50847.hmm -> /usr/local/lib/python3.8/dist-packages/inmembrane/protocols/gram_pos_profiles
copying build/lib/inmembrane/protocols/gram_pos_profiles/NLPC_P60.hmm -> /usr/local/lib/python3.8/dist-packages/inmembrane/protocols/gram_pos_profiles
copying build/lib/inmembrane/protocols/gram_pos_profiles/GW2.hmm -> /usr/local/lib/python3.8/dist-packages/inmembrane/protocols/gram_pos_profiles
copying build/lib/inmembrane/protocols/gram_pos_profiles/GW3.hmm -> /usr/local/lib/python3.8/dist-packages/inmembrane/protocols/gram_pos_profiles
copying build/lib/inmembrane/protocols/gram_pos_profiles/Gram_pos_anchor.hmm -> /usr/local/lib/python3.8/dist-packages/inmembrane/protocols/gram_pos_profiles
copying build/lib/inmembrane/protocols/gram_pos_profiles/LPxTG.hmm -> /usr/local/lib/python3.8/dist-packages/inmembrane/protocols/gram_pos_profiles
copying build/lib/inmembrane/protocols/gram_pos_profiles/PG_binding_2.hmm -> /usr/local/lib/python3.8/dist-packages/inmembrane/protocols/gram_pos_profiles
copying build/lib/inmembrane/protocols/gram_pos_profiles/GW1.hmm -> /usr/local/lib/python3.8/dist-packages/inmembrane/protocols/gram_pos_profiles
copying build/lib/inmembrane/protocols/gram_pos_profiles/PG_binding_3.hmm -> /usr/local/lib/python3.8/dist-packages/inmembrane/protocols/gram_pos_profiles
copying build/lib/inmembrane/protocols/gram_pos_profiles/CW_binding_2.hmm -> /usr/local/lib/python3.8/dist-packages/inmembrane/protocols/gram_pos_profiles
copying build/lib/inmembrane/protocols/gram_pos_profiles/LysM.hmm -> /usr/local/lib/python3.8/dist-packages/inmembrane/protocols/gram_pos_profiles
copying build/lib/inmembrane/protocols/gram_pos_profiles/PG_binding_1.hmm -> /usr/local/lib/python3.8/dist-packages/inmembrane/protocols/gram_pos_profiles
copying build/lib/inmembrane/protocols/gram_pos_profiles/CW_binding_1.hmm -> /usr/local/lib/python3.8/dist-packages/inmembrane/protocols/gram_pos_profiles
copying build/lib/inmembrane/tests/test_misc.py -> /usr/local/lib/python3.8/dist-packages/inmembrane/tests
copying build/lib/inmembrane/tests/signalp_scrape_web/input.fasta -> /usr/local/lib/python3.8/dist-packages/inmembrane/tests/signalp_scrape_web
copying build/lib/inmembrane/tests/test_bomp_web.py -> /usr/local/lib/python3.8/dist-packages/inmembrane/tests
copying build/lib/inmembrane/tests/test_signalp_scrape_web.py -> /usr/local/lib/python3.8/dist-packages/inmembrane/tests
copying build/lib/inmembrane/tests/tmhmm_scrape_web/input.fasta -> /usr/local/lib/python3.8/dist-packages/inmembrane/tests/tmhmm_scrape_web
copying build/lib/inmembrane/tests/__init__.py -> /usr/local/lib/python3.8/dist-packages/inmembrane/tests
copying build/lib/inmembrane/tests/test_signalp4.py -> /usr/local/lib/python3.8/dist-packages/inmembrane/tests
copying build/lib/inmembrane/tests/memsat3/input.fasta -> /usr/local/lib/python3.8/dist-packages/inmembrane/tests/memsat3
copying build/lib/inmembrane/tests/test_tatfind_web.py -> /usr/local/lib/python3.8/dist-packages/inmembrane/tests
copying build/lib/inmembrane/tests/test_hmmsearch3.py -> /usr/local/lib/python3.8/dist-packages/inmembrane/tests
copying build/lib/inmembrane/tests/tatfind_web/input.fasta -> /usr/local/lib/python3.8/dist-packages/inmembrane/tests/tatfind_web
copying build/lib/inmembrane/tests/signalp4/input.fasta -> /usr/local/lib/python3.8/dist-packages/inmembrane/tests/signalp4
copying build/lib/inmembrane/tests/test_tmbetadisc_rbf_web.py -> /usr/local/lib/python3.8/dist-packages/inmembrane/tests
copying build/lib/inmembrane/tests/test_tmhmm_scrape_web.py -> /usr/local/lib/python3.8/dist-packages/inmembrane/tests
copying build/lib/inmembrane/tests/PluginTestBase.py -> /usr/local/lib/python3.8/dist-packages/inmembrane/tests
copying build/lib/inmembrane/tests/test_lipop_scrape_web.py -> /usr/local/lib/python3.8/dist-packages/inmembrane/tests
copying build/lib/inmembrane/tests/test_tmhmm.py -> /usr/local/lib/python3.8/dist-packages/inmembrane/tests
copying build/lib/inmembrane/tests/test_lipop1.py -> /usr/local/lib/python3.8/dist-packages/inmembrane/tests
copying build/lib/inmembrane/tests/lipop_scrape_web/input.fasta -> /usr/local/lib/python3.8/dist-packages/inmembrane/tests/lipop_scrape_web
copying build/lib/inmembrane/tests/lipop1/input.fasta -> /usr/local/lib/python3.8/dist-packages/inmembrane/tests/lipop1
copying build/lib/inmembrane/tests/test_memsat3.py -> /usr/local/lib/python3.8/dist-packages/inmembrane/tests
copying build/lib/inmembrane/tests/tmhmm/input.fasta -> /usr/local/lib/python3.8/dist-packages/inmembrane/tests/tmhmm
copying build/lib/inmembrane/tests/hmmsearch3/input.fasta -> /usr/local/lib/python3.8/dist-packages/inmembrane/tests/hmmsearch3
copying build/lib/inmembrane/tests/tmbetadisc_rbf_web/input.fasta -> /usr/local/lib/python3.8/dist-packages/inmembrane/tests/tmbetadisc_rbf_web
copying build/lib/inmembrane/tests/bomp_web/input.fasta -> /usr/local/lib/python3.8/dist-packages/inmembrane/tests/bomp_web
copying build/lib/inmembrane/__init__.py -> /usr/local/lib/python3.8/dist-packages/inmembrane
copying build/lib/inmembrane/plugins/bomp_web.py -> /usr/local/lib/python3.8/dist-packages/inmembrane/plugins
copying build/lib/inmembrane/plugins/hmmsearch3.py -> /usr/local/lib/python3.8/dist-packages/inmembrane/plugins
copying build/lib/inmembrane/plugins/tmbetadisc_rbf_web.py -> /usr/local/lib/python3.8/dist-packages/inmembrane/plugins
copying build/lib/inmembrane/plugins/lipop_scrape_web.py -> /usr/local/lib/python3.8/dist-packages/inmembrane/plugins
copying build/lib/inmembrane/plugins/__init__.py -> /usr/local/lib/python3.8/dist-packages/inmembrane/plugins
copying build/lib/inmembrane/plugins/tmbhunt_web.py -> /usr/local/lib/python3.8/dist-packages/inmembrane/plugins
copying build/lib/inmembrane/plugins/tmhmm_web.py -> /usr/local/lib/python3.8/dist-packages/inmembrane/plugins
copying build/lib/inmembrane/plugins/memsat3.py -> /usr/local/lib/python3.8/dist-packages/inmembrane/plugins
copying build/lib/inmembrane/plugins/tmhmm.py -> /usr/local/lib/python3.8/dist-packages/inmembrane/plugins
copying build/lib/inmembrane/plugins/lipop1.py -> /usr/local/lib/python3.8/dist-packages/inmembrane/plugins
copying build/lib/inmembrane/plugins/tmhmm_scrape_web.py -> /usr/local/lib/python3.8/dist-packages/inmembrane/plugins
copying build/lib/inmembrane/plugins/lipop_web.py -> /usr/local/lib/python3.8/dist-packages/inmembrane/plugins
copying build/lib/inmembrane/plugins/signalp4.py -> /usr/local/lib/python3.8/dist-packages/inmembrane/plugins
copying build/lib/inmembrane/plugins/signalp_scrape_web.py -> /usr/local/lib/python3.8/dist-packages/inmembrane/plugins
copying build/lib/inmembrane/plugins/tatfind_web.py -> /usr/local/lib/python3.8/dist-packages/inmembrane/plugins
copying build/lib/inmembrane/helpers.py -> /usr/local/lib/python3.8/dist-packages/inmembrane
byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/protocols/gram_pos.py to gram_pos.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/protocols/__init__.py to __init__.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/protocols/gram_neg.py to gram_neg.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/tests/test_misc.py to test_misc.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/tests/test_bomp_web.py to test_bomp_web.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/tests/test_signalp_scrape_web.py to test_signalp_scrape_web.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/tests/__init__.py to __init__.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/tests/test_signalp4.py to test_signalp4.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/tests/test_tatfind_web.py to test_tatfind_web.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/tests/test_hmmsearch3.py to test_hmmsearch3.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/tests/test_tmbetadisc_rbf_web.py to test_tmbetadisc_rbf_web.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/tests/test_tmhmm_scrape_web.py to test_tmhmm_scrape_web.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/tests/PluginTestBase.py to PluginTestBase.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/tests/test_lipop_scrape_web.py to test_lipop_scrape_web.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/tests/test_tmhmm.py to test_tmhmm.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/tests/test_lipop1.py to test_lipop1.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/tests/test_memsat3.py to test_memsat3.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/__init__.py to __init__.cpython-38.pyc
  File "/usr/local/lib/python3.8/dist-packages/inmembrane/__init__.py", line 115
    def process(params):
    ^
SyntaxError: import * only allowed at module level

byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/plugins/bomp_web.py to bomp_web.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/plugins/hmmsearch3.py to hmmsearch3.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/plugins/tmbetadisc_rbf_web.py to tmbetadisc_rbf_web.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/plugins/lipop_scrape_web.py to lipop_scrape_web.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/plugins/__init__.py to __init__.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/plugins/tmbhunt_web.py to tmbhunt_web.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/plugins/tmhmm_web.py to tmhmm_web.cpython-38.pyc
  File "/usr/local/lib/python3.8/dist-packages/inmembrane/plugins/tmhmm_web.py", line 75
    newseqid = `seqcount` + re.sub(r'[^\w]', "", seqid)
               ^
SyntaxError: invalid syntax

byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/plugins/memsat3.py to memsat3.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/plugins/tmhmm.py to tmhmm.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/plugins/lipop1.py to lipop1.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/plugins/tmhmm_scrape_web.py to tmhmm_scrape_web.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/plugins/lipop_web.py to lipop_web.cpython-38.pyc
  File "/usr/local/lib/python3.8/dist-packages/inmembrane/plugins/lipop_web.py", line 88
    newseqid = `seqcount` + re.sub(r'[^\w]', "", seqid)
               ^
SyntaxError: invalid syntax

byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/plugins/signalp4.py to signalp4.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/plugins/signalp_scrape_web.py to signalp_scrape_web.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/plugins/tatfind_web.py to tatfind_web.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/inmembrane/helpers.py to helpers.cpython-38.pyc
  File "/usr/local/lib/python3.8/dist-packages/inmembrane/helpers.py", line 89
    print s
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(s)?

running install_scripts
copying build/scripts-3.8/inmembrane_scan -> /usr/local/bin
changing mode of /usr/local/bin/inmembrane_scan to 755
running install_egg_info
Removing /usr/local/lib/python3.8/dist-packages/inmembrane-0.95.0.egg-info
Writing /usr/local/lib/python3.8/dist-packages/inmembrane-0.95.0.egg-info

**Comment by pansapiens** [comment]
Fair warning - inmembrane hasn't been maintained in many years and is probably not something you should spend too much time trying to get running at this point (it might be time this repo is put into a 'archived' state). Many of the web services it used have since gone offline or changed their APIs such the inmembrane would need to be updated to work with them.

The main problem here is that the version of `python` you are using is 3.x and inmembrane only supports (the now deprecated) Python 2.x.
I would also suggest not installing as `sudo` - I know that's what it says in the README, but it was bad advice.
If you want to persist, instead create a virtualenv or conda environment containing Python 2.7, then try running: `python2 setup.py install`. You'll also need to [install the local binary dependencies](https://github.com/boscoh/inmembrane#installing-dependencies) since most of the web service equivalents no longer work.

Personally, I would save your time, not attempt to use inmembrane and move on to find an alternative.

**Comment by Dimpledavray287** [comment]
Thanks for the prompt reply.
Can you please suggest to me what could be the best alternative to identify
subcellular location of proteins.
As of  now i have sorted two pSORTb, CELLO2GO
Thanks & Regards
Dimple Davray
